baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "nl-nl"
title = "Hugo testsite"
theme = "ubuntu-nl"
MetaDataFormat = "yaml"

# Menu's voor linkjes die geen pagina's van Hugo zijn. De link naar de homepage kan evt. ook op een andere manier
[[menu.mainnav]]
  name = "Ubuntu"
  weight = -100
  identifier = "ubuntu"
  url = "/"

[[menu.mainnav]]
  name = "Documentatie"
  weight = 10
  identifier = "documentatie"
  parent = "ondersteuning"
  url = "http://wiki.ubuntu-nl.org"

[[menu.mainnav]]
  name = "Forum"
  weight = 20
  identifier = "forum"
  parent = "ondersteuning"
  url = "https://forum.ubuntu-nl.org"

  [[menu.mainnav]]
    name = "Mailinglijst"
    weight = 50
    parent = "ondersteuning"
    url = "https://lists.ubuntu.com/mailman/listinfo/ubuntu-nl"

  [[menu.mainnav]]
    name = "Gemeenschap"
    weight = 20
    identifier = "gemeenschap"
    url = "/gemeenschap"

    [[menu.mainnav]]
      name = "Wiki"
      weight = 30
      parent = "gemeenschap"
      url = "http://wiki.ubuntu-nl.org/community"

    [[menu.mainnav]]
      name = "Live Chat"
      weight = 40
      parent = "gemeenschap"
      identifier = "live-chat-gemeenschap"
      url = "/live-chat"

    [[menu.mainnav]]
      name = "Agenda"
      weight = 30
      identifier = "agenda"
      url = "/agenda"

    [[menu.mainnav]]
      name = "Planet"
      weight = 10
      parent = "nieuws"
      url = "/planet"

    [[menu.mainnav]]
      name = "Facebook"
      weight = 30
      parent = "nieuws"
      url = "https://www.facebook.com/ubuntunederlands"
